### ISSUE TITLE
`make mrproper` removes `.config` file

### ISSUE THREAD

**Issue by 7aitsev** [slackwarecn-slackbuilds/kernel-self-build#1]
The [`kernel.SlackBuild`](https://github.com/slackwarecn-slackbuilds/kernel-self-build/blob/69e8283bab17dfd2d64fab96cea4e5ddad837a4e/kernel.SlackBuild) script creates a copy of the running kernel configuration and then removes this file as a result of execution `make mrproper`.

https://github.com/slackwarecn-slackbuilds/kernel-self-build/blob/69e8283bab17dfd2d64fab96cea4e5ddad837a4e/kernel.SlackBuild#L48-L56

**Comment by mdrights** [comment]
The two issues are both fixed.
Thank you very much :+1:
